# escape=`
FROM microsoft/nanoserver

ARG VS_REMOTE_DEBUGGER_PATH

ADD $VS_REMOTE_DEBUGGER_PATH "c:\windows"

WORKDIR "c:\app"
ADD x64\Debug .

ENTRYPOINT start /B msvsmon.exe /FallbackLoadRemoteManagedPdbs /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:36000 && AzureIoTEdgeModule.exe